[package]
name = "toktor_impl"
author = "Daniele Cruciani <daniele@smartango.com>"
version = "0.1.0"
edition = "2021"

[lib]
name = "toktor_impl"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version="2.0.28", features = ["full", "parsing", "visit"] }
